### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by risuvoo** [juno-w/vuecordion#1]
Question icon not change  and icon rotation not working

**Comment by juno-w** [comment]
@meXuvo This accordion uses Tailwind CSS. Are you using Tailwind CSS?

**Comment by risuvoo** [comment]
@juno-w yes i am using tailwindcss with  tailwind jit compiler

**Comment by juno-w** [comment]
Can you show me the steps how to reproduce the issue?

**Comment by risuvoo** [comment]
I solve thia problem thank you for your response
